"""update user model

Revision ID: 4c2acd2bfe43
Revises: e4a923612ab9
Create Date: 2024-12-19 15:51:41.427793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2acd2bfe43'
down_revision = 'e4a923612ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fav_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_color', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
